# Generated by Django 4.2.1 on 2023-10-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bydliste',
            name='pojistenci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.pojistenci'),
        ),
        migrations.AddField(
            model_name='pojistenci',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
