# Generated by Django 4.2.1 on 2023-10-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0002_bydliste_pojistenci_pojistenci_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bydliste',
            name='pojistenci',
        ),
        migrations.AddField(
            model_name='pojistenci',
            name='bydliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.bydliste'),
        ),
        migrations.CreateModel(
            name='Smlouvy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_smlouvy', models.CharField(max_length=20)),
                ('datum_pocatek', models.DateField()),
                ('datum_vyroci', models.DateField()),
                ('typ_smlouvy', models.CharField(choices=[('majetek', 'Majetek'), ('auto', 'Auto'), ('zivot', 'Život'), ('investice', 'Investice'), ('mojefirma', 'Moje Firma'), ('podnikatele', 'Podnikatelé'), ('prumysl', 'Průmysl'), ('drony', 'Drony'), ('flotila', 'Flotila')], max_length=20)),
                ('pojisteni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.pojistenci')),
            ],
        ),
    ]
