# Generated by Django 4.2.1 on 2023-10-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0003_remove_bydliste_pojistenci_pojistenci_bydliste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojistenci',
            name='user',
        ),
        migrations.AlterField(
            model_name='pojistenci',
            name='bydliste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.bydliste'),
        ),
    ]
