# Generated by Django 4.2.1 on 2023-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0004_remove_pojistenci_user_alter_pojistenci_bydliste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smlouvy',
            name='pojisteni',
        ),
        migrations.AddField(
            model_name='pojistenci',
            name='smlouva',
            field=models.ManyToManyField(to='myclient.smlouvy'),
        ),
    ]
