# Generated by Django 4.2.1 on 2023-10-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0005_remove_smlouvy_pojisteni_pojistenci_smlouva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smlouvy',
            new_name='Smlouva',
        ),
    ]
