# Generated by Django 4.2.1 on 2023-10-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0006_rename_smlouvy_smlouva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenci',
            name='bydliste',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.bydliste'),
        ),
        migrations.RemoveField(
            model_name='pojistenci',
            name='smlouva',
        ),
        migrations.AddField(
            model_name='pojistenci',
            name='smlouva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.smlouva'),
        ),
    ]
