# Generated by Django 4.2.1 on 2023-10-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0007_alter_pojistenci_bydliste_remove_pojistenci_smlouva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojistenci',
            name='smlouva',
        ),
        migrations.AddField(
            model_name='smlouva',
            name='pojistenec',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.pojistenci'),
        ),
    ]
