# Generated by Django 4.2.1 on 2023-10-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0009_remove_pojistenci_bydliste_bydliste_pojistenec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bydliste',
            name='pojistenec',
        ),
        migrations.AddField(
            model_name='pojistenci',
            name='bydliste',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.bydliste'),
        ),
    ]
