# Generated by Django 4.2.1 on 2023-10-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0010_remove_bydliste_pojistenec_pojistenci_bydliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenci',
            name='rodne_cislo',
            field=models.CharField(default='000000/0000', max_length=11),
        ),
    ]
