# Generated by Django 4.2.1 on 2023-10-21 07:47

from django.db import migrations, models
import myclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0012_remove_pojistenci_rodne_cislo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenci',
            name='cislo_pojistence',
            field=models.IntegerField(unique=True, validators=[myclient.models.validate_cislo_pojistence]),
        ),
        migrations.AlterField(
            model_name='smlouva',
            name='cislo_smlouvy',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
