# Generated by Django 4.2.1 on 2023-10-21 09:10

from django.db import migrations, models
import myclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0014_alter_pojistenci_cislo_pojistence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smlouva',
            name='cislo_smlouvy',
            field=models.CharField(error_messages={'unique': 'Smlouva s tímto číslem již existuje.'}, max_length=9, unique=True, validators=[myclient.models.validate_cislo_smlouvy]),
        ),
    ]
