# Generated by Django 4.2.1 on 2023-10-21 10:04

from django.db import migrations, models
import myclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0015_alter_smlouva_cislo_smlouvy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smlouva',
            name='cislo_smlouvy',
            field=models.IntegerField(error_messages={'unique': 'Smlouva s tímto číslem již existuje.'}, unique=True, validators=[myclient.models.validate_cislo_smlouvy]),
        ),
    ]
